---
deployment:
  tasks:
    - export NODE_ENV=production
    - npm ci
    - npx prisma generate --schema src/prisma/schema.prisma
    - npx prisma migrate deploy --schema src/prisma/schema.prisma
    - npm run build
    - mkdir -p tmp
    - touch tmp/restart.txt

