import { PrismaClient, Role } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: "postgresql://neondb_owner:npg_jzQACkco0T8S@ep-broad-truth-a1v49nhu-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require",
    },
  },
});

async function main() {
  // Users
  const password = await bcrypt.hash("Passw0rd!", 10);
  const [admin, lead, staff1, staff2, staff3, staff4, user1, user2, user3, user4, user5, user6, user7, user8] = await Promise.all([
    // Admin
    prisma.user.upsert({
      where: { email: "admin@it.local" },
      update: {},
      create: { 
        username: "admin",
        email: "admin@it.local", 
        password: password, 
        role: Role.ADMIN, 
        name: "Nguyễn Văn Admin",
        phone: "0901234567",
        department: "IT"
      },
    }),
    // IT Lead
    prisma.user.upsert({
      where: { email: "lead@it.local" },
      update: {},
      create: { 
        username: "lead",
        email: "lead@it.local", 
        password: password, 
        role: Role.IT_LEAD, 
        name: "Trần Thị Lead",
        phone: "0901234568",
        department: "IT"
      },
    }),
    // IT Staff
    prisma.user.upsert({
      where: { email: "staff1@it.local" },
      update: {},
      create: { 
        username: "staff1",
        email: "staff1@it.local", 
        password: password, 
        role: Role.IT_STAFF, 
        name: "Lê Văn Staff 1",
        phone: "0901234569",
        department: "IT"
      },
    }),
    prisma.user.upsert({
      where: { email: "staff2@it.local" },
      update: {},
      create: { 
        username: "staff2",
        email: "staff2@it.local", 
        password: password, 
        role: Role.IT_STAFF, 
        name: "Phạm Thị Staff 2",
        phone: "0901234570",
        department: "IT"
      },
    }),
    prisma.user.upsert({
      where: { email: "staff3@it.local" },
      update: {},
      create: { 
        username: "staff3",
        email: "staff3@it.local", 
        password: password, 
        role: Role.IT_STAFF, 
        name: "Hoàng Văn Staff 3",
        phone: "0901234571",
        department: "IT"
      },
    }),
    prisma.user.upsert({
      where: { email: "staff4@it.local" },
      update: {},
      create: { 
        username: "staff4",
        email: "staff4@it.local", 
        password: password, 
        role: Role.IT_STAFF, 
        name: "Vũ Thị Staff 4",
        phone: "0901234572",
        department: "IT"
      },
    }),
    // Regular Users
    prisma.user.upsert({
      where: { email: "user1@it.local" },
      update: {},
      create: { 
        username: "user1",
        email: "user1@it.local", 
        password: password, 
        role: Role.USER, 
        name: "Nguyễn Thị User 1",
        phone: "0901234573",
        department: "Kế toán"
      },
    }),
    prisma.user.upsert({
      where: { email: "user2@it.local" },
      update: {},
      create: { 
        username: "user2",
        email: "user2@it.local", 
        password: password, 
        role: Role.USER, 
        name: "Trần Văn User 2",
        phone: "0901234574",
        department: "Nhân sự"
      },
    }),
    prisma.user.upsert({
      where: { email: "user3@it.local" },
      update: {},
      create: { 
        username: "user3",
        email: "user3@it.local", 
        password: password, 
        role: Role.USER, 
        name: "Lê Thị User 3",
        phone: "0901234575",
        department: "Marketing"
      },
    }),
    prisma.user.upsert({
      where: { email: "user4@it.local" },
      update: {},
      create: { 
        username: "user4",
        email: "user4@it.local", 
        password: password, 
        role: Role.USER, 
        name: "Phạm Văn User 4",
        phone: "0901234576",
        department: "Kinh doanh"
      },
    }),
    prisma.user.upsert({
      where: { email: "user5@it.local" },
      update: {},
      create: { 
        username: "user5",
        email: "user5@it.local", 
        password: password, 
        role: Role.USER, 
        name: "Hoàng Thị User 5",
        phone: "0901234577",
        department: "Sản xuất"
      },
    }),
    prisma.user.upsert({
      where: { email: "user6@it.local" },
      update: {},
      create: { 
        username: "user6",
        email: "user6@it.local", 
        password: password, 
        role: Role.USER, 
        name: "Vũ Văn User 6",
        phone: "0901234578",
        department: "Chất lượng"
      },
    }),
    prisma.user.upsert({
      where: { email: "user7@it.local" },
      update: {},
      create: { 
        username: "user7",
        email: "user7@it.local", 
        password: password, 
        role: Role.USER, 
        name: "Đặng Thị User 7",
        phone: "0901234579",
        department: "Logistics"
      },
    }),
    prisma.user.upsert({
      where: { email: "user8@it.local" },
      update: {},
      create: { 
        username: "user8",
        email: "user8@it.local", 
        password: password, 
        role: Role.USER, 
        name: "Bùi Văn User 8",
        phone: "0901234580",
        department: "Tài chính"
      },
    }),
  ]);

  // KPI config default
  await prisma.kPIConfig.upsert({
    where: { id: "default" },
    update: {},
    create: {
      id: "default",
    },
  });

  // Create employees
  const employees = [
    {
      fullName: "Huỳnh Thanh Long",
      dateOfBirth: new Date("2002-10-25"),
      gender: "Nam",
      hometown: "Gia Lai",
      religion: "Không",
      ethnicity: "Kinh",
      startDate: new Date("2025-07-12"),
      primaryPhone: "0867432507",
      secondaryPhone: "0867432507",
      personalEmail: "it.htlong25@gmail.com",
      companyEmail: "longht@smartservices.com.vn",
      placeOfBirth: "Gia Lai",
      permanentAddress: "Thôn Thắng Kiên, Xã Đề Gi, Tỉnh Gia Lai",
      temporaryAddress: "76E, Đường số 36, Khu Phố 18, Phường Thủ Đức, Tp. Hồ Chí Minh",
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Chính thức",
      avatar: null,
    },
    {
      fullName: "Đoàn Trí Khương",
      dateOfBirth: new Date("2004-03-13"),
      gender: "Nam",
      hometown: "Đồng Tháp",
      religion: "Không",
      ethnicity: "Kinh",
      startDate: new Date("2025-04-24"),
      primaryPhone: "0842190719",
      secondaryPhone: null,
      personalEmail: "trikhuongdoan@gmail.com",
      companyEmail: "khuongdt@smartservices.com.vn",
      placeOfBirth: "Đồng Tháp",
      permanentAddress: "Tổ 5, Ấp An Thọ, Xã An Phước, Tỉnh Đồng Tháp",
      temporaryAddress: "326, Nguyền Văn Khối, Phường Thông Tây Hội, TP. Hồ Chí Minh",
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Thử việc",
      avatar: null,
    },
    {
      fullName: "Trần Nguyễn Anh Khoa",
      dateOfBirth: new Date("1996-04-09"),
      gender: "Nam",
      hometown: "Gia Lai",
      religion: "Công Giáo",
      ethnicity: "Kinh",
      startDate: new Date("2025-02-19"),
      primaryPhone: "0779115679",
      secondaryPhone: null,
      personalEmail: "akhoa.rm96@gmail.com",
      companyEmail: "khoatna@smartservices.com.vn",
      placeOfBirth: "Hồ Chí Minh",
      permanentAddress: "258 Hiền Vương, Phường Phú Thạnh, TP. Hồ Chí Minh",
      temporaryAddress: null,
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Chính thức",
      avatar: null,
    },
    {
      fullName: "Trần Anh Vũ",
      dateOfBirth: new Date("2002-07-04"),
      gender: "Nam",
      hometown: "Hồ Chí Minh",
      religion: "Không",
      ethnicity: "Kinh",
      startDate: new Date("2023-01-09"),
      primaryPhone: "0903570744",
      secondaryPhone: null,
      personalEmail: "poke742002@gmail.com",
      companyEmail: "vuta@smartservices.com.vn",
      placeOfBirth: "Hồ Chí Minh",
      permanentAddress: "170/8B Hoàng Văn Thụ, Khu phố 4, phường Đức Nhuận, TP. Hồ Chí Minh",
      temporaryAddress: "C7D/27E14, Ấp 42 Phạm Hùng, xã Bình Hưng Tp. Hồ Chí Minh",
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Chính thức",
      avatar: null,
    },
    {
      fullName: "Nguyễn Tấn Đạt",
      dateOfBirth: new Date("2002-02-03"),
      gender: "Nam",
      hometown: "DakLak",
      religion: "Phật",
      ethnicity: "Kinh",
      startDate: new Date("2025-04-21"),
      primaryPhone: "0833591894",
      secondaryPhone: null,
      personalEmail: "nguyentandat0002@gmail.com",
      companyEmail: "datnt@smartservices.com.vn",
      placeOfBirth: "Gia Lai",
      permanentAddress: "193/31 Nguyễn Văn Cừ, Phường Tân Lập, Buôn Ma Thuột, DakLak",
      temporaryAddress: null,
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Thử việc",
      avatar: null,
    },
    {
      fullName: "Trần Trọng Nghĩa",
      dateOfBirth: new Date("2002-02-06"),
      gender: "Nam",
      hometown: "Tây Ninh",
      religion: "Không",
      ethnicity: "Kinh",
      startDate: new Date("2025-05-26"),
      primaryPhone: "0356503352",
      secondaryPhone: null,
      personalEmail: "trannghia2062002@gmail.com",
      companyEmail: "nghiatt.sms@outlook.com",
      placeOfBirth: "Tây Ninh",
      permanentAddress: "Số 3438 QL22 ,P. An Tịnh, Tây Ninh",
      temporaryAddress: "266/13 Lê Trọng Tấn,P. Tây Thạnh, TP. HCM",
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Thử việc",
      avatar: null,
    },
    {
      fullName: "Nguyễn Ngọc Quế Trâm",
      dateOfBirth: new Date("2001-06-05"),
      gender: "Nữ",
      hometown: "Đồng Tháp",
      religion: "Không",
      ethnicity: "Kinh",
      startDate: new Date("2024-10-28"),
      primaryPhone: "0869319117",
      secondaryPhone: null,
      personalEmail: "quetram6521@gmail.com",
      companyEmail: "tramnnq@smartservices.com.vn",
      placeOfBirth: "Đồng Tháp",
      permanentAddress: "Ấp 6, xã Tân Đông, tỉnh Đồng Tháp",
      temporaryAddress: "273/40/4 Nguyễn Văn Đậu, P. Bình Lợi Trung, Tp HCM",
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Chính thức",
      avatar: null,
    },
    {
      fullName: "Nguyễn Trung Thu Hiền",
      dateOfBirth: new Date("2005-12-16"),
      gender: "Nữ",
      hometown: "Hà Nội",
      religion: "Không",
      ethnicity: "Kinh",
      startDate: new Date("2025-02-07"),
      primaryPhone: "0373910512",
      secondaryPhone: null,
      personalEmail: "nguyenhien2802@gmail.com",
      companyEmail: "hiennt.sms@outlook.com",
      placeOfBirth: "Hồ Chí Minh",
      permanentAddress: "108/18, Tô Hiệu, Phường Phú Thạnh, TP Hồ Chí Minh",
      temporaryAddress: "108/18 tô hiệu, phường phú thạnh (hiệp tân cũ), quận tân phú",
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Thử việc",
      avatar: null,
    },
    {
      fullName: "Đào Nguyễn Kim Ngọc",
      dateOfBirth: new Date("1998-01-04"),
      gender: "Nữ",
      hometown: "Hồ Chí Minh",
      religion: "Không",
      ethnicity: "Kinh",
      startDate: new Date("2025-02-06"),
      primaryPhone: "0933512955",
      secondaryPhone: null,
      personalEmail: "dnkimngoc0104@gmail.com",
      companyEmail: "ngocdnk@smartservices.com.vn",
      placeOfBirth: "Hồ Chí Minh",
      permanentAddress: "77/12 Kp Bình Đường 1, Phường Dĩ An, TP Hồ Chí Minh",
      temporaryAddress: "45/39 Bình Đường 1, P. Dĩ An, TP HCM",
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Thử việc",
      avatar: null,
    },
    {
      fullName: "Chế Thành Luân",
      dateOfBirth: new Date("1992-08-07"),
      gender: "Nam",
      hometown: "Quảng Ngãi",
      religion: "Không",
      ethnicity: "Kinh",
      startDate: new Date("2025-10-06"),
      primaryPhone: "0942291393",
      secondaryPhone: null,
      personalEmail: "chethanhluan@gmail.com",
      companyEmail: "luanct@smartservices.com.vn",
      placeOfBirth: "Quảng Ngãi",
      permanentAddress: "Thôn 2, Xã Mỏ Cày, Quảng Ngãi",
      temporaryAddress: "28/3/4 Văn Chung, Phường Tân Bình, TPHCM",
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Chính thức",
      avatar: null,
    },
    {
      fullName: "Trần Hoàng Phúc",
      dateOfBirth: new Date("1998-09-10"),
      gender: "Nam",
      hometown: "Hồ Chí Minh",
      religion: "Phật",
      ethnicity: "Kinh",
      startDate: new Date("2025-10-03"),
      primaryPhone: "0936762430",
      secondaryPhone: null,
      personalEmail: "tranhoangphuc943@gmail.com",
      companyEmail: "phucth@smartservices.com.vn",
      placeOfBirth: "Đồng Nai",
      permanentAddress: "Thôn Tân Hiệp 2, xã Phú Riềng, Đồng Nai",
      temporaryAddress: "138/11/19 Nguyễn Duy Cung Phường An Hội Tây, TP HCM",
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Chính thức",
      avatar: null,
    },
    {
      fullName: "Nguyễn Thành Đạt",
      dateOfBirth: new Date("2003-07-28"),
      gender: "Nam",
      hometown: "DakLak",
      religion: "Không",
      ethnicity: "Kinh",
      startDate: new Date("2025-05-16"),
      primaryPhone: "0384803776",
      secondaryPhone: null,
      personalEmail: "thanhdatnguyen715@gmail.com",
      companyEmail: "datnt.sms@outlook.com",
      placeOfBirth: "DakLak",
      permanentAddress: "Thôn Sơn Thọ, P. Bình Kiến, DakLak",
      temporaryAddress: "262 Lê Đức Thọ, Phường An Nhơn, TP. HCM",
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Thử việc",
      avatar: null,
    },
    {
      fullName: "Trần Công Vũ",
      dateOfBirth: new Date("2003-04-25"),
      gender: "Nam",
      hometown: "Nghệ An",
      religion: "Không",
      ethnicity: "Kinh",
      startDate: new Date("2025-06-24"),
      primaryPhone: "0902652241",
      secondaryPhone: null,
      personalEmail: "trancongvu2542003@gmail.com",
      companyEmail: "vutc.sms@outlook.com",
      placeOfBirth: "Nghệ An",
      permanentAddress: "129/17 Tân Phú 1, Phường Tân Đông Hiệp, TP Hồ Chí Minh",
      temporaryAddress: null,
      position: "Developer",
      department: "IT",
      status: "active",
      contractType: "Thử việc",
      avatar: null,
    },
  ];

  for (const employeeData of employees) {
    await prisma.employee.upsert({
      where: { companyEmail: employeeData.companyEmail },
      update: {},
      create: employeeData,
    });
  }

  console.log(`Created ${employees.length} employees`);

  // Create suppliers/partners
  const suppliers = [
    {
      fullCompanyName: "CÔNG TY TNHH CHIẾU SÁNG ĐIỆN TỬ ỨNG DỤNG",
      shortName: "AICe",
      address: "257 Giải Phóng, Phường Kim Liên, Quận Đống Đa, Hà Nội",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TRÁCH NHIỆM HỮU HẠN AMPERE COMPUTING VIETNAM",
      shortName: "AMPERE",
      address: "Lô D.01, đường Tân Thuận, khu chế xuất Tân Thuận, Phường Tân Thuận, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH AURECON VIỆT NAM",
      shortName: "AURECON",
      address: "Tầng 24 và 25, Tòa nhà Lim Tower III, Số 29A, Đường Nguyễn Đình Chiểu, Phường Tân Định, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY CỔ PHẦN ĐẦU TƯ TỔNG HỢP LIÊN VIỆT",
      shortName: "BASE TÂN PHÚ (Liên Việt)",
      address: "3/10A Hiền Vương, Phường Phú Thạnh, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH THƯƠNG MẠI KỸ THUẬT BCA",
      shortName: "BCA",
      address: "118 Cộng Hòa, Phường Tân Sơn Nhất, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH DEVEE ENTERTAINMENT",
      shortName: "DEVEE ENT",
      address: "Số 70 Hoàng Trọng Mậu, Khu dân cư Him Lam, Phường Tân Hưng, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY CỔ PHẦN DIPLOMAT",
      shortName: "DIPLOMAT",
      address: "76-78 Nguyễn Thị Minh Khai, Phường Xuân Hòa, TP. Hồ Chí Minh",
      contactPerson: "Mr. Duy",
      contactPhone: "0938012354",
    },
    {
      fullCompanyName: "CÔNG TY TNHH ELECTRONIC TRIPOD VIỆT NAM (BIÊN HÒA)",
      shortName: "ELECTRONIC TRIPOD VN",
      address: "Số 31, Đường 3A, KCN Biên Hòa 2, phường Trấn Biên, Tỉnh Đồng Nai",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH ELITE LONG THÀNH",
      shortName: "ELITE LONG THÀNH",
      address: "Lô D, KCN Lộc An - Bình Sơn, Xã Long Thành, Tỉnh Đồng Nai",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH DỊCH VỤ GIÁO DỤC EVEREST",
      shortName: "EVEREST EDU",
      address: "Số 38 Nguyễn Lâm, Phường Diên Hồng, TP Hồ Chí Minh",
      contactPerson: "Ms. Viên",
      contactPhone: "0968973005",
    },
    {
      fullCompanyName: "CÔNG TY TNHH CÔNG NGHỆ GFT VIỆT NAM",
      shortName: "GFT VN",
      address: "Phòng 02-115, Tầng 2, WeWork Lim Tower 3, Số 29A Nguyễn Đình Chiểu, Phường Tân Định, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH TIN HỌC GIA PHÚC KHANG.",
      shortName: "GIA PHÚC KHANG",
      address: "644/1 Đoàn Văn Bơ, Phường Xóm Chiếu, TP. Hồ Chí Minh",
      contactPerson: "Mr. Đức",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH HASKONINGDHV VIỆT NAM",
      shortName: "HASKONINGDHV VN",
      address: "Tầng 6, Tòa nhà Vista Tower, Số 628C Võ Nguyên Giáp, Phường An Khánh, TP. Hồ Chí Minh",
      contactPerson: "Mr. Thái",
      contactPhone: "0777911087",
    },
    {
      fullCompanyName: "CÔNG TY TNHH MỘT THÀNH VIÊN THƯƠNG MẠI DỊCH VỤ HỘI LỘC",
      shortName: "HỘI LỘC",
      address: "Số 609/13/23 Nguyễn Chí Thanh, Phường Phú An, TP. Hồ Chí Minh",
      contactPerson: "Ms. Nguyệt Lê",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY CỔ PHẦN HUDECO",
      shortName: "HUDECO",
      address: "496/32/30 Dương Quảng Hàm, Phường An Nhơn, Thành phố Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "TỔ CHỨC DI CƯ QUỐC TẾ",
      shortName: "IOM",
      address: "1B Phạm Ngọc Thạch, Phường Sài Gòn, TP. Hồ Chí Minh",
      contactPerson: "Ms. Như",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH LAPBEE",
      shortName: "LAPBEE",
      address: "Số 170 Đường Trương Công Định, Phường Tân Bình, TP. Hồ Chí Minh",
      contactPerson: "Mr. Hoàng",
      contactPhone: "0938491468",
    },
    {
      fullCompanyName: "Công Ty TNHH MTV TM -DV Tin Học Lê Huy",
      shortName: "LÊ HUY",
      address: "48 Chấn Hưng, Phường Tân Hòa, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "LOTTE VIETNAM COMPANY LIMITED (CÔNG TY TNHH LOTTE VIỆT NAM)",
      shortName: "LOTTE VN",
      address: "469 Nguyễn Hữu Thọ, Phường Tân Hưng, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH MAXLINK",
      shortName: "MAXLINK",
      address: "L17-11, Tầng 17, Tòa nhà Vincom Center, 72 Lê Thánh Tôn, Phường Sài Gòn, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY CỔ PHẦN GIẢI PHÁP MÁY CHỦ VIỆT",
      shortName: "MÁY CHỦ VIỆT",
      address: "196/1/8 Cộng Hòa, Phường Bảy Hiền, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH DỊCH VỤ TIN HỌC SIÊU TỐC (MEMORYZONE)",
      shortName: "MEMORYZONE",
      address: "4C Đồng Xoài, Phường Tân Bình, TP. Hồ Chí Minh",
      contactPerson: "Ms. Khanh",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH TRUNG TÂM PHÁT TRIỂN PHẦN MỀM VIỆT NAM",
      shortName: "NAB (Phát Triển Phần Mềm VN)",
      address: "Tầng 8, 9, 10, 11, 12 Tháp A, số 15 đường Trần Bạch Đằng, Phường An Khánh, TP. Hồ Chí Minh",
      contactPerson: "Ms. Thư",
      contactPhone: "0376556982",
    },
    {
      fullCompanyName: "CÔNG TY TNHH KỸ THUẬT THƯƠNG MẠI DỊCH VỤ NÉT VIỆT",
      shortName: "NETVIET",
      address: "187 Tôn Thất Thuyết, Phường Vĩnh Hội, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH VI TÍNH NGUYÊN KIM",
      shortName: "NGUYÊN KIM",
      address: "245b Trần Quang Khải, Phường Tân Định, TP. Hồ Chí Minh",
      contactPerson: "Ms. Chi",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH NHÂN SINH PHÚC",
      shortName: "NHÂN SINH PHÚC",
      address: "124 Hồng Hà, Phường Tân Sơn Hòa, TP. Hồ Chí Minh",
      contactPerson: "Mr. Anh",
      contactPhone: "0962737656",
    },
    {
      fullCompanyName: "CÔNG TY TNHH NIELSENIQ VIỆT NAM",
      shortName: "NIELSENIQ",
      address: "Lầu 4, Tòa nhà Centre Point, số 106, đường Nguyễn Văn Trỗi, Phường Phú Nhuận, TP. Hồ Chí Minh",
      contactPerson: "Mr. Duy",
      contactPhone: "0352701071",
    },
    {
      fullCompanyName: "CÔNG TY TNHH DỊCH VỤ VÀ GIẢI PHÁP CÔNG NGHỆ MỚI",
      shortName: "NTEC (Công Nghệ Mới)",
      address: "Tầng 12 - Tháp A2, Viettel Tower, 285 Cách Mạng Tháng Tám, Phường Hòa Hưng, TP. Hồ Chí Minh",
      contactPerson: "Mr. Khoa",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY CỔ PHẦN CÔNG NGHỆ NTG VIỆT NAM",
      shortName: "NTG VN",
      address: "Tầng 10, tòa Suced Tower, số 108 đường Nguyễn Hoàng, Phường Từ Liêm, Quận Nam Từ Liêm, Hà Nội",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "Công ty TNHH TM Âm Thanh Ánh Sáng Nội Thất PHAN NGUYỄN",
      shortName: "PHAN NGUYỄN",
      address: "406 Tân Sơn Nhì, Phường Tân Sơn Nhì, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY CỔ PHẦN DƯỢC PHẨM PHARMACITY",
      shortName: "PHARMACITY",
      address: "248A Nơ Trang Long, Phường Bình Thạnh, TP.HCM",
      contactPerson: "Ms. Quỳnh",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH QUẢNG TIN",
      shortName: "QUẢNG TIN",
      address: "Số 8 Đường số 12, Cư xá Chu Văn An, Phường Bình Thạnh, TP. Hồ Chí Minh",
      contactPerson: "Ms. Thúy",
      contactPhone: "0933198939",
    },
    {
      fullCompanyName: "CÔNG TY TNHH XI MĂNG SCG VIỆT NAM (CHI NHÁNH TP.HCM)",
      shortName: "SCG XI MĂNG VN (CN TPHCM)",
      address: "Số 117-119, Lý Chính Thắng, Phường Xuân Hòa, TP. Hồ Chí Minh.",
      contactPerson: "Mr. Giả",
      contactPhone: null,
    },
    {
      fullCompanyName: "SEARA SPORTS SYSTEMS VIETNAM CO., LTD.",
      shortName: "SEARA",
      address: "227 Nam Kỳ Khởi Nghĩa, Phường Nhiêu Lộc, TP. Hồ Chí Minh",
      contactPerson: "Ms. Nhung",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY CỔ PHẦN GIẢI PHÁP SIÊU VIỆT",
      shortName: "SIÊU VIỆT",
      address: "109/45 Lê Quốc Hưng, Phường Xóm Chiếu, TP. Hồ Chí Minh",
      contactPerson: "Ms. Trang",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH CÔNG NGHỆ - DỊCH VỤ SMART SERVICES",
      shortName: "SMART SERVICES",
      address: "Lầu 7, Tòa nhà MIOS Building, Số 121 Hoàng Hoa Thám, Phường Gia Định, TP. Hồ Chí Minh",
      contactPerson: "Mr. Khoa",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH THƯƠNG MẠI VÀ ĐẦU TƯ TẬP ĐOÀN TÂM SEN",
      shortName: "TÂM SEN",
      address: "Số 41, Ngõ 52, Phố Tô Ngọc Vân, Phường Tây Hồ, Quận Tây Hồ, Hà Nội",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH TATA COFFEE VIỆT NAM",
      shortName: "TATA COFFEE VN",
      address: "Số 12 VSIP II-A đường số 32, Khu công nghiệp Việt Nam-Singapore II-A, Phường Vĩnh Tân, TP. Hồ Chí Minh",
      contactPerson: "Mr. Sam",
      contactPhone: null,
    },
    {
      fullCompanyName: "Công ty TNHH Tin Học Thành Nhân",
      shortName: "THÀNH NHÂN",
      address: "174-176-178-180 Bùi Thị Xuân, Phường Bến Thành, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH TOTALENERGIES LPG VIỆT NAM",
      shortName: "TOTALENERGIES LPG VN",
      address: "89/7E Đường Bến Nghé, Phường Tân Thuận, TP. Hồ Chí Minh",
      contactPerson: "Mr. Trung",
      contactPhone: "0365604499",
    },
    {
      fullCompanyName: "CÔNG TY TNHH TOTALENERGIES MARKETING VIỆT NAM",
      shortName: "TOTALENERGIES MKG VN",
      address: "Số 111A, Đường Pasteur, Phường Sài Gòn, TP. Hồ Chí Minh",
      contactPerson: "Mr. Đoài",
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH UGREEN GROUP VIỆT NAM",
      shortName: "UGREEN SG (Vi Tính SG)",
      address: "Tầng 12 (1206), CitiLight Tower, Số 45, Đường Võ Thị Sáu, Phường Tân Định, TP. Hồ Chí Minh",
      contactPerson: "Mr. Lâm",
      contactPhone: "0703097056",
    },
    {
      fullCompanyName: "CÔNG TY CỔ PHẦN VANTAGE LOGISTICS",
      shortName: "VANTAGE LOGISTICS",
      address: "Phòng 6.01, Tầng 6 RiverGate Residence, Số 151-155 Đường Bến Vân Đồn, Phường Khánh Hội, TP. Hồ Chí Minh",
      contactPerson: "Mr. Công",
      contactPhone: "0973299901",
    },
    {
      fullCompanyName: "CÔNG TY TNHH TM - DV CÔNG NGHỆ VINA TECH",
      shortName: "VINA TECH",
      address: "6 Đặng Thai Mai, Phường Phú Nhuận, TP. Hồ Chí Minh",
      contactPerson: null,
      contactPhone: null,
    },
    {
      fullCompanyName: "CÔNG TY TNHH WUERTH DỊCH VỤ CÔNG NGHIỆP",
      shortName: "WUERTH VN",
      address: "Phòng 402, Tầng 4, Tòa nhà CentrePoint, 106 Nguyễn Văn Trỗi, Phường Phú Nhuận, TP. Hồ Chí Minh",
      contactPerson: "Ms. Thùy",
      contactPhone: "0931495596",
    },
  ];

  for (const supplierData of suppliers) {
    await prisma.partner.create({
      data: supplierData,
    });
  }

  console.log(`Created ${suppliers.length} suppliers`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });


